FROM node:20-slim AS build

RUN npm install -g openapi-typescript@7.5.1 typescript

COPY openapi.yaml /src/openapi.yaml

RUN openapi-typescript /src/openapi.yaml -o /output/index.ts

FROM scratch

COPY --from=build /output /output
ENTRYPOINT [ "/output" ]
