FROM openapitools/openapi-generator-cli:v7.10.0 AS build

COPY openapi.yaml /src/openapi.yaml
RUN /usr/local/bin/docker-entrypoint.sh generate -i /src/openapi.yaml -g typescript -o /output


FROM scratch

COPY --from=build /output /output
ENTRYPOINT [ "/output" ]
